issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - misspell
    - revive
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/sefaphlvn/bigbang
  gosec:
    excludes:
      - G115
  misspell:
    locale: US
  testifylint:
    disable:
      - float-compare
      - go-require
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - len
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call

  unparam:
    check-exported: false

run:
  timeout: 10m
