# Build stage
FROM golang:1.22.12-alpine AS builder

ARG ENVOY_VERSION
ARG BIGBANG_CONTROL_PLANE_VERSION

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo \
    -ldflags "-X github.com/sefaphlvn/bigbang/pkg/version.Version=${ENVOY_VERSION} -X github.com/sefaphlvn/bigbang/pkg/version.ControlPlaneVersion=${BIGBANG_CONTROL_PLANE_VERSION}" \
    -o bigbang .

# Final stage
FROM alpine:3.21.3

RUN apk --no-cache update && apk --no-cache upgrade && \
    apk add --no-cache ca-certificates openssl

WORKDIR /root/

COPY --from=builder /app/bigbang .

EXPOSE 8099 18000

ENTRYPOINT ["./bigbang"]
