package models

type GTypes string

const (
	APITypePrefix                GTypes = "type.googleapis.com/"
	BootStrap                    GTypes = "envoy.config.bootstrap.v3.Bootstrap"
	HTTPConnectionManager        GTypes = "envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
	Router                       GTypes = "envoy.extensions.filters.http.router.v3.Router"
	Cluster                      GTypes = "envoy.config.cluster.v3.Cluster"
	Listener                     GTypes = "envoy.config.listener.v3.Listener"
	Endpoint                     GTypes = "envoy.config.endpoint.v3.ClusterLoadAssignment"
	Route                        GTypes = "envoy.config.route.v3.RouteConfiguration"
	VirtualHost                  GTypes = "envoy.config.route.v3.VirtualHost"
	TCPProxy                     GTypes = "envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
	FluentdAccessLog             GTypes = "envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig"
	FileAccessLog                GTypes = "envoy.extensions.access_loggers.file.v3.FileAccessLog"
	StdoutAccessLog              GTypes = "envoy.extensions.access_loggers.stream.v3.StdoutAccessLog"
	StdErrAccessLog              GTypes = "envoy.extensions.access_loggers.stream.v3.StderrAccessLog"
	DownstreamTLSContext         GTypes = "envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
	UpstreamTLSContext           GTypes = "envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
	TLSCertificate               GTypes = "envoy.extensions.transport_sockets.tls.v3.TlsCertificate"
	CertificateValidationContext GTypes = "envoy.extensions.transport_sockets.tls.v3.CertificateValidationContext"
	TLSSessionTicketKeys         GTypes = "envoy.extensions.transport_sockets.tls.v3.TlsSessionTicketKeys"
	GenericSecret                GTypes = "envoy.extensions.transport_sockets.tls.v3.GenericSecret"
	HealthCheckEventFileSink     GTypes = "envoy.extensions.health_check.event_sinks.file.v3.HealthCheckEventFileSink"
	BasicAuth                    GTypes = "envoy.extensions.filters.http.basic_auth.v3.BasicAuth"
	BasicAuthPerRoute            GTypes = "envoy.extensions.filters.http.basic_auth.v3.BasicAuthPerRoute"
	Cors                         GTypes = "envoy.extensions.filters.http.cors.v3.Cors"
	CorsPolicy                   GTypes = "envoy.extensions.filters.http.cors.v3.CorsPolicy"
	BandwidthLimit               GTypes = "envoy.extensions.filters.http.bandwidth_limit.v3.BandwidthLimit"
	Compressor                   GTypes = "envoy.extensions.filters.http.compressor.v3.Compressor"
	CompressorPerRoute           GTypes = "envoy.extensions.filters.http.compressor.v3.CompressorPerRoute"
	GzipCompressor               GTypes = "envoy.extensions.compression.gzip.compressor.v3.Gzip"
	BrotliCompressor             GTypes = "envoy.extensions.compression.brotli.compressor.v3.Brotli"
	ZstdCompressor               GTypes = "envoy.extensions.compression.zstd.compressor.v3.Zstd"
	HTTPProtocolOptions          GTypes = "envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
	Lua                          GTypes = "envoy.extensions.filters.http.lua.v3.Lua"
	LuaPerRoute                  GTypes = "envoy.extensions.filters.http.lua.v3.LuaPerRoute"
	Buffer                       GTypes = "envoy.extensions.filters.http.buffer.v3.Buffer"
	BufferPerRoute               GTypes = "envoy.extensions.filters.http.buffer.v3.BufferPerRoute"
	AdaptiveConcurrency          GTypes = "envoy.extensions.filters.http.adaptive_concurrency.v3.AdaptiveConcurrency"
	RBAC                         GTypes = "envoy.extensions.filters.network.rbac.v3.RBAC"
	HTTPRBAC                     GTypes = "envoy.extensions.filters.http.rbac.v3.RBAC"
	HTTPRBACPerRoute             GTypes = "envoy.extensions.filters.http.rbac.v3.RBACPerRoute"
	URITemplateMatch             GTypes = "envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig"
	AdmissionControl             GTypes = "envoy.extensions.filters.http.admission_control.v3.AdmissionControl"
	HeaderBasedSessionState      GTypes = "envoy.extensions.http.stateful_session.header.v3.HeaderBasedSessionState"
	CookieBasedSessionState      GTypes = "envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState"
	StatefulSession              GTypes = "envoy.extensions.filters.http.stateful_session.v3.StatefulSession"
	StatefulSessionPerRoute      GTypes = "envoy.extensions.filters.http.stateful_session.v3.StatefulSessionPerRoute"
	CsrfPolicy                   GTypes = "envoy.extensions.filters.http.csrf.v3.CsrfPolicy"
	ListenerLocalRatelimit       GTypes = "envoy.extensions.filters.listener.local_ratelimit.v3.LocalRateLimit"
	ListenerHttpInspector        GTypes = "envoy.extensions.filters.listener.http_inspector.v3.HttpInspector"
	ListenerOriginalDst          GTypes = "envoy.extensions.filters.listener.original_dst.v3.OriginalDst"
	ListenerOriginalSrc          GTypes = "envoy.extensions.filters.listener.original_src.v3.OriginalSrc"
	ListenerTlsInspector         GTypes = "envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
	ListenerDnsFilter            GTypes = "envoy.extensions.filters.udp.dns_filter.v3.DnsFilterConfig"
	ListenerProxyProtocol        GTypes = "envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
	ListeneProxyProtocol         GTypes = "envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
	ConnectionLimit              GTypes = "envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit"
	NetworkLocalRatelimit        GTypes = "envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit"
	HttpLocalRatelimit           GTypes = "envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit"
	OAuth2                       GTypes = "envoy.extensions.filters.http.oauth2.v3.OAuth2"
)
