ElchiAddress: "demo.elchi.io"
BigbangAddress: "bigbang.elchi.io"
ServerPort: "8099"
PokePort: "8080"

MongoDB_Hosts: navigazer.lfh5hlh.mongodb.net
MongoDB_Username: "navigazer"
MongoDB_Password: "3s7qObVXRpt2wWUT"
MongoDB_Database: "navigazer"
MongoDB_Scheme: "mongodb+srv"
MongoDB_Port:
MongoDB_ReplicaSet: ""
MongoDB_TimeoutSeconds: "10"

Log_Level: debug          # debug, info, warn, error
Log_Formatter: text      # json, text
Log_ReportCaller: "false"
