BIGBANG_ADDRESS: "${BIGBANG_ADDRESS}"
BIGBANG_TLS_ENABLED: "${BIGBANG_TLS_ENABLED}"
BIGBANG_REST_SERVER_PORT: "${BIGBANG_REST_SERVER_PORT}"
BIGBANG_GRPC_POKE_PORT: "${BIGBANG_GRPC_POKE_PORT}"
BIGBANG_GRPC_NODE_COUNT: "${BIGBANG_GRPC_NODE_COUNT}"

MONGODB_HOSTS: "${MONGODB_HOSTS}"
MONGODB_USERNAME: "${MONGODB_USERNAME}"
MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
MONGODB_DATABASE: "${MONGODB_DATABASE}"
MONGODB_SCHEME: "${MONGODB_SCHEME}"
MONGODB_PORT: 
MONGODB_REPLICASET: ""
MONGODB_TIMEOUTSECONDS: "${MONGODB_TIMEOUTSECONDS}"

LOG_LEVEL: debug          # debug, info, warn, error
LOG_FORMATTER: text       # json, text
LOG_REPORTCALLER: "false"
