ServerPort: 80
GrpcService: localhost:8080
MongoDB:
  #Hosts: ["navigazer.lfh5hlh.mongodb.net"]
  Hosts: ["localhost:27017"]
  Username: ""
  #Password: "3s7qObVXRpt2wWUT"
  Password: ""
  Database: "navigazer"
  #Scheme: "mongodb+srv"
  Scheme: "mongodb"
  Port:
  ReplicaSet: ""
  TimeoutSeconds: 10
Log:
  Level: debug          # debug, info, warn, error
  Formatter: text      # json, text
  ReportCaller: false