BIGBANG_ADDRESS: "${BIGBANG_ADDRESS}"
BIGBANG_PORT: "${BIGBANG_PORT}"
BIGBANG_TLS_ENABLED: "${BIGBANG_TLS_ENABLED}"
BIGBANG_GRPC_NODE_COUNT: "${BIGBANG_GRPC_NODE_COUNT}"
BIGBANG_REST_NODE_COUNT: "${BIGBANG_REST_NODE_COUNT}"
BIGBANG_ENABLE_DEMO: "${BIGBANG_ENABLE_DEMO}"
BIGBANG_INTERNAL_COMMUNICATION: "false"
BIGBANG_INTERNAL_ADDRESS_PORT: "envoy-service.elchi-platform.svc.cluster.local:8080"
BIGBANG_VERSIONS:
  - v1.32.3
  - v1.33.0
MONGODB_HOSTS: "${MONGODB_HOSTS}"
MONGODB_USERNAME: "${MONGODB_USERNAME}"
MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
MONGODB_DATABASE: "${MONGODB_DATABASE}"
MONGODB_SCHEME: "${MONGODB_SCHEME}"
MONGODB_PORT: ""
MONGODB_REPLICASET: ""
MONGODB_TIMEOUTMS: "${MONGODB_TIMEOUTMS}"
MONGODB_TLS_ENABLED: "${MONGODB_TLS_ENABLED}"

LOG_LEVEL: debug # debug, info, warn, error
LOG_FORMATTER: text # json, text
LOG_REPORTCALLER: "false"

SMTP_PASSWORD: "${SMTP_PASSWORD}"