name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t bigbang-rest .

      - name: Tag Docker image
        run: |
          docker tag bigbang-rest ${{ secrets.DOCKER_USERNAME }}/bigbang-rest:latest

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bigbang-rest:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DEPLOY_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H 68.183.216.216 >> ~/.ssh/known_hosts

      - name: Pull Docker image on DigitalOcean
        run: |
          ssh root@68.183.216.216 "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}"
          ssh root@68.183.216.216 "docker pull ${{ secrets.DOCKER_USERNAME }}/bigbang-rest:latest"

      - name: Run Docker container on DigitalOcean
        run: |
          ssh root@68.183.216.216 "docker run -d -p 8080:80 --name bigbang-rest-container ${{ secrets.DOCKER_USERNAME }}/bigbang-rest:latest server-rest"