name: Deploy to Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set unique tags
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Fill config-prod.yaml with environment variables
        run: |
          export BIGBANG_ADDRESS=${{ vars.BIGBANG_ADDRESS }}
          export BIGBANG_PORT=${{ vars.BIGBANG_PORT }}
          export BIGBANG_TLS_ENABLED=${{ vars.BIGBANG_TLS_ENABLED }}
          export BIGBANG_GRPC_NODE_COUNT=1
          export BIGBANG_REST_NODE_COUNT=1
          export BIGBANG_ENABLE_DEMO=${{ vars.BIGBANG_ENABLE_DEMO }}
          export MONGODB_HOSTS=${{ vars.MONGODB_HOSTS }}
          export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}
          export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
          export MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}
          export MONGODB_SCHEME=${{ vars.MONGODB_SCHEME }}
          export MONGODB_PORT=${{ vars.MONGODB_PORT }}
          export MONGODB_REPLICASET=${{ vars.MONGODB_REPLICASET }}
          export MONGODB_TIMEOUTSECONDS=${{ vars.MONGODB_TIMEOUTSECONDS }}
          export MONGODB_TLS_ENABLED=${{ vars.MONGODB_TLS_ENABLED }}
          export LOG_LEVEL=${{ vars.LOG_LEVEL }}
          export LOG_FORMATTER=${{ vars.LOG_FORMATTER }}
          export LOG_REPORTCALLER=${{ vars.LOG_REPORTCALLER }}
          
          envsubst < .configs/config-prod.yaml > .configs/config-prod.yaml.filled
          mv .configs/config-prod.yaml.filled .configs/config-prod.yaml

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bigbang:${{ env.TAG }} .

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bigbang:${{ env.TAG }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DEPLOY_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H 68.183.216.216 >> ~/.ssh/known_hosts

      - name: Deploy gRPC container on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker stop bigbang-grpc-container || true && \
            docker rm bigbang-grpc-container || true && \
            docker run -d -p 18000:18000 -p 8098:8098 --name bigbang-grpc-container ${{ secrets.DOCKER_USERNAME }}/bigbang:${{ env.TAG }} ./main server-grpc"

      - name: Deploy Rest container on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker stop bigbang-rest-container || true && \
            docker rm bigbang-rest-container || true && \
            docker run -d -p 8099:8099 --name bigbang-rest-container ${{ secrets.DOCKER_USERNAME }}/bigbang:${{ env.TAG }} ./main server-rest"