name: Deploy to Demo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set unique tags
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Fill config-prod.yaml with environment variables
        run: |
          export BIGBANG_ADDRESS=${{ vars.BIGBANG_ADDRESS }}
          export BIGBANG_PORT=${{ vars.BIGBANG_PORT }}
          export BIGBANG_TLS_ENABLED=${{ vars.BIGBANG_TLS_ENABLED }}
          export BIGBANG_GRPC_NODE_COUNT=1
          export BIGBANG_REST_NODE_COUNT=1
          export BIGBANG_ENABLE_DEMO=${{ vars.BIGBANG_ENABLE_DEMO }}
          export MONGODB_HOSTS=${{ vars.MONGODB_HOSTS }}
          export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}
          export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
          export MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}
          export MONGODB_SCHEME=${{ vars.MONGODB_SCHEME }}
          export MONGODB_PORT=${{ vars.MONGODB_PORT }}
          export MONGODB_REPLICASET=${{ vars.MONGODB_REPLICASET }}
          export MONGODB_TIMEOUTSECONDS=${{ vars.MONGODB_TIMEOUTSECONDS }}
          export MONGODB_TLS_ENABLED=${{ vars.MONGODB_TLS_ENABLED }}
          export LOG_LEVEL=${{ vars.LOG_LEVEL }}
          export LOG_FORMATTER=${{ vars.LOG_FORMATTER }}
          export LOG_REPORTCALLER=${{ vars.LOG_REPORTCALLER }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          
          envsubst < .configs/config-prod.yaml > .configs/config-prod.yaml.filled
          mv .configs/config-prod.yaml.filled .configs/config-prod.yaml

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DEPLOY_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H 68.183.216.216 >> ~/.ssh/known_hosts

      - name: Copy config file to server
        run: |
          ssh root@68.183.216.216 "mkdir -p /root/.configs"
          scp .configs/config-prod.yaml root@68.183.216.216:/root/.configs/config-prod.yaml

      - name: Deploy gRPC container (Envoy 1.32.3) on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker pull spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.32.3 && \
            docker stop bigbang-grpc-container-v1_32_3 || true && \
            docker rm bigbang-grpc-container-v1_32_3 || true && \
            docker run --pull always -d -p 18000:18000 -v /root/.configs/config-prod.yaml:/root/.configs/config-prod.yaml --name bigbang-grpc-container-v1_32_3 spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.32.3 server-grpc"

      - name: Deploy Rest container (Envoy 1.32.3) on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker pull spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.32.3 && \
            docker stop bigbang-rest-container-v1_32_3 || true && \
            docker rm bigbang-rest-container-v1_32_3 || true && \
            docker run --pull always -d -p 8099:8099 -v /root/.configs/config-prod.yaml:/root/.configs/config-prod.yaml --name bigbang-rest-container-v1_32_3 spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.32.3 server-rest"

      - name: Deploy gRPC container (Envoy 1.33.0) on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker pull spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.33.0 && \
            docker stop bigbang-grpc-container-v1_33_0 || true && \
            docker rm bigbang-grpc-container-v1_33_0 || true && \
            docker run --pull always -d -p 18001:18000 -v /root/.configs/config-prod.yaml:/root/.configs/config-prod.yaml --name bigbang-grpc-container-v1_33_0 spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.33.0 server-grpc"

      - name: Deploy Rest container (Envoy 1.33.0) on DigitalOcean
        run: |
          ssh root@68.183.216.216 "\
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
            docker pull spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.33.0 && \
            docker stop bigbang-rest-container-v1_33_0 || true && \
            docker rm bigbang-rest-container-v1_33_0 || true && \
            docker run --pull always -d -p 8199:8099 -v /root/.configs/config-prod.yaml:/root/.configs/config-prod.yaml --name bigbang-rest-container-v1_33_0 spehlivan/bigbang:v0.1.0-v0.13.4-envoy1.33.0 server-rest"