name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_DEPLOY_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H 68.183.216.216 >> ~/.ssh/known_hosts

      - name: Build REST Docker image
        run: |
          docker build --build-arg MODE=server-rest -t bigbang-rest .

      - name: Build gRPC Docker image
        run: |
          docker build --build-arg MODE=server-grpc -t bigbang-grpc .

      - name: Deploy REST application to DigitalOcean
        run: |
          scp bigbang-rest root@68.183.216.216:/root/
          ssh root@68.183.216.216 "docker run -d -p 8080:80 --name bigbang-rest-container /root/bigbang-rest server-rest"

      - name: Deploy gRPC application to DigitalOcean
        run: |
          scp bigbang-grpc root@68.183.216.216:/root/
          ssh root@68.183.216.216 "docker run -d -p 9090:8080 --name bigbang-grpc-container /root/bigbang-grpc server-grpc"