name: Build and Push Images

on:
  workflow_dispatch:
    inputs:
      envoy_versions:
        description: 'Control Plane versions (comma separated)'
        required: true
        default: 'v0.13.4-envoy1.33.0,v0.13.4-envoy1.33.2,v0.13.4-envoy1.32.3'
        type: string
      platforms:
        description: 'Target platforms (comma separated)'
        required: true
        type: choice
        options:
          - 'linux/amd64'
          - 'linux/arm64'
          - 'linux/amd64,linux/arm64'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: bigbang
  GO_CONTROL_PLANE_PACKAGE: github.com/sefaphlvn/versioned-go-control-plane
  GO_CONTROL_PLANE_ENVOY_PACKAGE: github.com/sefaphlvn/versioned-go-control-plane/envoy

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Set Project Version
        run: echo "PROJECT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Checkout release tag
        uses: actions/checkout@v4
        with:
          ref: v${{ env.PROJECT_VERSION }}
          path: release
          token: ${{ secrets.GH_PAT }}

      - name: Clean workspace
        run: |
          rm -rf release/Dockerfile-release || true
          cp Dockerfile-release release/

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ github.event.inputs.platforms }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push images
        working-directory: release
        env:
          DOCKER_BUILDKIT: 1
        run: |
          # Convert comma-separated versions to array
          IFS=',' read -ra CONTROL_PLANE_VERSIONS <<< "${{ github.event.inputs.envoy_versions }}"
          
          # Process each control plane version
          for CONTROL_PLANE_VERSION in "${CONTROL_PLANE_VERSIONS[@]}"; do
            # Trim whitespace
            CONTROL_PLANE_VERSION=$(echo $CONTROL_PLANE_VERSION | xargs)
            
            echo "Processing Control Plane version: ${CONTROL_PLANE_VERSION}"
            
            # Extract Envoy version from the full version string
            ENVOY_VERSION=$(echo $CONTROL_PLANE_VERSION | sed -n 's/.*envoy\([0-9.]*\)/\1/p')
            
            # Update go.mod for both packages
            go mod edit -require="${GO_CONTROL_PLANE_PACKAGE}@${CONTROL_PLANE_VERSION}"
            go mod edit -require="${GO_CONTROL_PLANE_ENVOY_PACKAGE}@v${ENVOY_VERSION}"
            go mod tidy
            
            # Set image tags
            IMAGE_NAME="${DOCKER_USERNAME}/${DOCKER_IMAGE}"
            IMAGE_TAG="${IMAGE_NAME}:v${PROJECT_VERSION}-${CONTROL_PLANE_VERSION}"
            LATEST_TAG="${IMAGE_NAME}:latest"
            
            # Build and push
            docker buildx build \
              --no-cache \
              --platform ${{ github.event.inputs.platforms }} \
              --build-arg "ENVOY_VERSION=v${ENVOY_VERSION}" \
              --build-arg "BIGBANG_CONTROL_PLANE_VERSION=bigbang-${PROJECT_VERSION}-${CONTROL_PLANE_VERSION}" \
              -t "${IMAGE_TAG}" \
              -t "${LATEST_TAG}" \
              -f Dockerfile-release \
              --push \
              .
            
            echo "✅ Control Plane version ${CONTROL_PLANE_VERSION} completed"
            
            # Reset go.mod changes for next iteration
            git checkout -- go.mod go.sum
          done 